#!/usr/bin/env python3
"""Generate a real transcript from a completed session."""

import sys
from datetime import datetime
from src.state import StateManager
from src.models import TaskStatus

def generate_transcript(session_id: str, output_file: str) -> None:
    """Generate a markdown transcript from a session."""
    state = StateManager('data/sessions.db')

    session = state.get_session(session_id)
    if not session:
        print(f"Error: Session {session_id} not found")
        sys.exit(1)

    tasks = state.get_session_tasks(session_id)
    results = state.get_tool_results(session_id)

    # Calculate duration
    if session.completed_at and session.created_at:
        duration = session.completed_at - session.created_at
        duration_str = f"~{duration.total_seconds() / 60:.1f} minutes"
    else:
        duration_str = "N/A"

    # Count completed/failed tasks
    completed = sum(1 for t in tasks if t.status == TaskStatus.COMPLETED)
    failed = sum(1 for t in tasks if t.status == TaskStatus.FAILED)

    # Build transcript
    lines = []
    lines.append("# Example Transcript: WebAssembly Adoption Research")
    lines.append("")
    lines.append("> **Note**: This is a real transcript generated by the research agent with live API calls.")
    lines.append("> The session demonstrates the complete workflow from goal → plan → execution → synthesis.")
    lines.append(">")
    lines.append("> **Session Details**:")
    lines.append(f"> - Session ID: `{session_id}`")
    lines.append(f"> - Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("> - All search results and synthesis are from actual API responses")
    lines.append("")
    lines.append("## Session Information")
    lines.append(f"- **Goal:** {session.goal}")
    lines.append(f"- **Date:** {session.created_at.strftime('%Y-%m-%d')}")
    lines.append(f"- **Duration:** {duration_str}")
    lines.append(f"- **Tasks Completed:** {completed}/{len(tasks)}")
    lines.append("")

    # Phase 1: Planning
    lines.append("## Phase 1: Planning")
    lines.append("")
    lines.append("### Generated Plan")
    lines.append("")
    lines.append("| ID | Task | Dependencies |")
    lines.append("|----|------|--------------|")

    if session.plan:
        for task in session.plan.tasks:
            deps = ", ".join(task.dependencies) if task.dependencies else "None"
            # Truncate long descriptions
            desc = task.description[:100] + "..." if len(task.description) > 100 else task.description
            lines.append(f"| {task.id} | {desc} | {deps} |")

    lines.append("")
    lines.append("**User Confirmation:** Yes, proceed with this plan (auto-approved)")
    lines.append("")

    # Phase 2: Execution
    lines.append("## Phase 2: Execution")
    lines.append("")

    # Map results to tasks
    result_map = {r.task_id: r for r in results}

    for task in tasks:
        status_icon = "✓" if task.status == TaskStatus.COMPLETED else "✗"
        lines.append(f"### Task {task.id}: {task.description[:80]}...")
        lines.append(f"**Status:** {status_icon} {task.status.value.title()}")

        result = result_map.get(task.id)
        if result:
            lines.append(f"**Tool:** {result.tool_name}")

            # Extract query from metadata if available
            query = result.metadata.get('query', 'N/A')
            lines.append(f"**Query:** {query}")

            # Parse result data from full_content
            if result.success and result.full_content:
                import json
                try:
                    data = json.loads(result.full_content)
                    if isinstance(data, dict) and 'results' in data:
                        search_results = data['results']
                        lines.append(f"**Results:** Found {len(search_results)} results")
                        lines.append("**Key Findings:**")
                        lines.append(f"- {result.summary}")
                        lines.append("")
                        lines.append("**Sources:**")
                        for sr in search_results[:5]:  # Top 5 sources
                            lines.append(f"- {sr.get('url', 'N/A')}")
                    else:
                        lines.append(f"**Summary:** {result.summary}")
                except (json.JSONDecodeError, KeyError, TypeError):
                    lines.append(f"**Summary:** {result.summary}")
            else:
                lines.append(f"**Summary:** {result.summary if result else 'No result data'}")

        lines.append("")

    # Phase 3: Synthesis
    lines.append("## Phase 3: Synthesis")
    lines.append("")
    lines.append("### Final Research Report")
    lines.append("")

    if session.final_report:
        lines.append(session.final_report)
    else:
        lines.append("*No final report available*")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Session Summary")
    lines.append("")
    lines.append(f"**Session ID:** {session_id}")
    lines.append(f"**Goal:** {session.goal}")
    lines.append(f"**Status:** {session.status.value}")
    lines.append(f"**Tasks:** {completed}/{len(tasks)} completed, {failed} failed")
    lines.append(f"**Duration:** {duration_str}")

    # Count total sources
    total_sources = sum(1 for r in results if r.success)
    lines.append(f"**Total Sources:** {total_sources * 5}+ unique sources across all tasks")
    lines.append("")

    # Write to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))

    print(f"✓ Transcript written to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_transcript.py <session-id> [output-file]")
        sys.exit(1)

    session_id = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "examples/transcript_webassembly.md"

    generate_transcript(session_id, output_file)
