#!/usr/bin/env python3
"""Generate a real transcript from a completed session."""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

from src.models import TaskStatus
from src.state import StateManager

# Anchor database path to repo root, not CWD
REPO_ROOT = Path(__file__).parent.parent
DB_PATH = REPO_ROOT / "data" / "sessions.db"


def _sanitize_filename(text: str, max_length: int = 50) -> str:
    """Convert text to a safe filename component."""
    safe = re.sub(r"[^\w\s-]", "", text.lower())
    safe = re.sub(r"[-\s]+", "_", safe)
    return safe[:max_length].strip("_")


def _count_unique_source_urls(results: list) -> int:
    """Count unique metadata source URLs from successful results only."""
    urls: set[str] = set()
    for result in results:
        if not result.success:
            continue

        for source in result.metadata.get("sources", []):
            if isinstance(source, dict):
                url = source.get("url", "")
            else:
                url = str(source)
            if url:
                urls.add(url)

    return len(urls)


def generate_transcript(session_id: str, output_file: str) -> None:
    """Generate a markdown transcript from a session."""
    state = StateManager(str(DB_PATH))

    session = state.get_session(session_id)
    if not session:
        print(f"Error: Session {session_id} not found")
        sys.exit(1)

    tasks = state.get_session_tasks(session_id)
    results = state.get_tool_results(session_id)

    if session.completed_at and session.created_at:
        duration = session.completed_at - session.created_at
        duration_str = f"~{duration.total_seconds() / 60:.1f} minutes"
    else:
        duration_str = "N/A"

    completed = sum(1 for t in tasks if t.status == TaskStatus.COMPLETED)
    failed = sum(1 for t in tasks if t.status == TaskStatus.FAILED)

    lines = []
    lines.append(f"# Example Transcript: {session.goal}")
    lines.append("")
    lines.append("> **Note**: This is a real transcript generated by the research agent with live API calls.")
    lines.append("> The session demonstrates the complete workflow from goal → plan → execution → synthesis.")
    lines.append(">")
    lines.append("> **Session Details**:")
    lines.append(f"> - Session ID: `{session_id}`")
    lines.append(f"> - Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("> - All search results and synthesis are from actual API responses")
    lines.append("")
    lines.append("## Session Information")
    lines.append(f"- **Goal:** {session.goal}")
    lines.append(f"- **Date:** {session.created_at.strftime('%Y-%m-%d')}")
    lines.append(f"- **Duration:** {duration_str}")
    lines.append(f"- **Tasks Completed:** {completed}/{len(tasks)}")
    lines.append("")

    lines.append("## Phase 1: Planning")
    lines.append("")
    lines.append("### Generated Plan")
    lines.append("")
    lines.append("| ID | Task | Dependencies |")
    lines.append("|----|------|--------------|")

    if session.plan:
        for task in session.plan.tasks:
            deps = ", ".join(task.dependencies) if task.dependencies else "None"
            desc = task.description[:100] + "..." if len(task.description) > 100 else task.description
            lines.append(f"| {task.id} | {desc} | {deps} |")

    lines.append("")
    lines.append("**User Confirmation:** Yes, proceed with this plan (auto-approved)")
    lines.append("")

    lines.append("## Phase 2: Execution")
    lines.append("")

    result_map = {r.task_id: r for r in results}

    for task in tasks:
        status_icon = "✓" if task.status == TaskStatus.COMPLETED else "✗"
        lines.append(f"### Task {task.id}: {task.description[:80]}...")
        lines.append(f"**Status:** {status_icon} {task.status.value.title()}")

        result = result_map.get(task.id)
        if result:
            lines.append(f"**Tool:** {result.tool_name}")
            query = result.metadata.get("query", "N/A")
            lines.append(f"**Query:** {query}")

            if result.success and result.full_content:
                try:
                    data = json.loads(result.full_content)
                    if isinstance(data, dict) and "results" in data:
                        search_results = data["results"]
                        lines.append(f"**Results:** Found {len(search_results)} results")
                        lines.append("**Key Findings:**")
                        lines.append(f"- {result.summary}")
                        lines.append("")
                        lines.append("**Sources:**")
                        for search_result in search_results[:5]:
                            lines.append(f"- {search_result.get('url', 'N/A')}")
                    else:
                        lines.append(f"**Summary:** {result.summary}")
                except (json.JSONDecodeError, KeyError, TypeError):
                    lines.append(f"**Summary:** {result.summary}")
            else:
                lines.append(f"**Summary:** {result.summary if result else 'No result data'}")

        lines.append("")

    lines.append("## Phase 3: Synthesis")
    lines.append("")
    lines.append("### Final Research Report")
    lines.append("")

    if session.final_report:
        lines.append(session.final_report)
    else:
        lines.append("*No final report available*")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Session Summary")
    lines.append("")
    lines.append(f"**Session ID:** {session_id}")
    lines.append(f"**Goal:** {session.goal}")
    lines.append(f"**Status:** {session.status.value}")
    lines.append(f"**Tasks:** {completed}/{len(tasks)} completed, {failed} failed")
    lines.append(f"**Duration:** {duration_str}")

    total_sources = _count_unique_source_urls(results)
    lines.append(f"**Total Sources:** {total_sources} unique sources across all tasks")
    lines.append("")

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"✓ Transcript written to {output_file}")


def main() -> None:
    """CLI entry point for transcript generation."""
    if len(sys.argv) < 2:
        print("Usage: python generate_transcript.py <session-id> [output-file]")
        sys.exit(1)

    session_id = sys.argv[1]

    if len(sys.argv) > 2:
        output_file = sys.argv[2]
    else:
        state = StateManager(str(DB_PATH))
        session = state.get_session(session_id)
        if session and session.goal:
            safe_goal = _sanitize_filename(session.goal)
            output_file = str(REPO_ROOT / "examples" / f"transcript_{safe_goal}.md")
        else:
            safe_id = _sanitize_filename(session_id)
            output_file = str(REPO_ROOT / "examples" / f"transcript_{safe_id}.md")

    generate_transcript(session_id, output_file)


if __name__ == "__main__":
    main()
